### ISSUE TITLE
Undefined variable: id

### ISSUE THREAD

**Issue by shaperman** [Skidriam/yii2_test#1]
in /yii2_test/yii2/frontend/views/site/index.php at line 13

**Comment by Skidriam** [comment]
Это сразу на входе вышло?
![Снимок](https://user-images.githubusercontent.com/41430767/63170267-9a8f4a80-c041-11e9-9ccb-fc762c9ff812.PNG) Структура директории такая?
index.php находится в public.
В случае пустой БД должно выглядеть так 
![изображение](https://user-images.githubusercontent.com/41430767/63170439-ec37d500-c041-11e9-9373-9124b170bb3d.png)

**Comment by shaperman** [comment]
Не важно где это вышло - я вижу в коде, что контроллер SiteController/index не передаёт переменную $id во view index.

```php
return $this->render('index', ['cityes'=>$cityes]);
```
Здесь ведь нет переменной id.

**Comment by Skidriam** [comment]
Убрал его. Он там в принципе не нужен был, остаток от чего то.
